# Generated by Django 5.1.2 on 2025-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AlterField(
            model_name='batch',
            name='Batch_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='Section_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
