# Generated by Django 5.1.2 on 2024-11-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='users.course'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='deo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='users.deo'),
        ),
    ]
