# Generated by Django 5.1.2 on 2025-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_batch_id_remove_section_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
