# Generated by Django 5.1.2 on 2024-11-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacher_password_remove_teacher_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='section',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherPreference',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
