# Generated by Django 5.1.2 on 2025-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_course_id_alter_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
