# Generated by Django 5.1.2 on 2025-01-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_room_id_alter_room_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_ID',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
