# Generated by Django 5.1.2 on 2025-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_course_is_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcourseteacherassignment',
            name='Section_ID',
        ),
        migrations.RemoveField(
            model_name='batchcourseteacherassignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teachercourseassignment',
            name='id',
        ),
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Assignment_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='Assignment_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
