# Generated by Django 5.1.2 on 2025-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_batchcourseteacherassignment_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='Discipline',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
