# Generated by Django 5.1.2 on 2025-02-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcourseteacherassignment',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_course_teacher_assignments', to='users.section'),
        ),
    ]
