# Generated by Django 5.1.2 on 2025-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_batchcourseteacherassignment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_fullname',
            field=models.CharField(default='Computer Communication Networks', max_length=500),
            preserve_default=False,
        ),
    ]
