# Generated by Django 5.1.2 on 2025-03-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_course_course_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Batch_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='users.batch'),
        ),
    ]
