# Generated by Django 5.1.2 on 2025-03-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_course_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Batch_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_course_teacher_assignments', to='users.batch'),
        ),
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Course_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_course_teacher_assignments', to='users.course'),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='Course_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='users.course'),
        ),
    ]
