# Generated by Django 5.1.2 on 2025-03-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_batchcourseteacherassignment_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Batch_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_course_teacher_assignments', to='users.batch'),
        ),
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Course_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_course_teacher_assignments', to='users.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Batch_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.batch'),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='Course_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='users.course'),
        ),
    ]
