# Generated by Django 5.1.2 on 2025-03-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_batchcourseteacherassignment_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Batch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
