# Generated by Django 5.1.2 on 2025-03-22 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcourseteacherassignment',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_course_teacher_assignments', to='users.section'),
        ),
    ]
