# Generated by Django 5.1.2 on 2025-03-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_batchcourseteacherassignment_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='username',
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
