# Generated by Django 5.1.2 on 2025-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_advisor_deo_alter_advisor_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_code',
            field=models.CharField(max_length=20),
        ),
    ]
