# Generated by Django 5.1.2 on 2025-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Max_classes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
