# Generated by Django 5.1.2 on 2025-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_teacher_max_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
    ]
