# Generated by Django 5.1.2 on 2025-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_teacher_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Archived',
        ),
        migrations.AddField(
            model_name='course',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
    ]
