# Generated by Django 5.1.2 on 2025-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_batchcourseteacherassignment_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Max_classes_per_day',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
