# Generated by Django 5.1.2 on 2025-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_course_max_classes_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Non_Credit',
            field=models.BooleanField(default=False),
        ),
    ]
