# Generated by Django 5.1.2 on 2024-11-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_timetable_batch_remove_timetable_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_classes_per_day', models.PositiveIntegerField(default=4, help_text='Maximum number of classes the teacher can handle per day')),
                ('health_limitations', models.TextField(blank=True, help_text='Any health constraints for the teacher', null=True)),
                ('locked_schedule_slots', models.JSONField(blank=True, help_text="Locked time slots that cannot be changed by the AI scheduler (e.g., {'Monday': ['08:00-09:00']})", null=True)),
                ('additional_preferences', models.JSONField(blank=True, default=dict, help_text='Additional or unknown preferences (stored as key-value pairs)', null=True)),
                ('unavailable_days', models.CharField(blank=True, help_text="Days when the teacher is unavailable (e.g., 'Monday, Wednesday')", max_length=100, null=True)),
                ('preferred_rooms', models.ManyToManyField(blank=True, related_name='preferred_by_teachers', to='users.room')),
                ('preferred_subjects', models.ManyToManyField(blank=True, related_name='preferred_by_teachers', to='users.course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
