# Generated by Django 5.1.2 on 2025-01-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_batchcourseteacherassignment_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compensatory_ID', models.IntegerField(unique=True)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreferenceConstraints',
            fields=[
                ('Preference_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Start_Time', models.CharField(blank=True, max_length=10, null=True)),
                ('End_Time', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Lab_or_Theory', models.CharField(choices=[('lab', 'Lab'), ('theory', 'Theory')], max_length=10)),
                ('Multimedia_requirement', models.BooleanField(default=False)),
                ('Speaker', models.BooleanField(default=False)),
                ('Hard_constraint', models.BooleanField(default=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRoomPreference',
            fields=[
                ('Room_Preference_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Floor', models.CharField(blank=True, max_length=10, null=True)),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timetable_ID', models.IntegerField(unique=True)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('Batch_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('Section_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail_ID', models.IntegerField(unique=True)),
                ('Day', models.CharField(blank=True, max_length=10, null=True)),
                ('Start_Time', models.CharField(blank=True, max_length=10, null=True)),
                ('End_Time', models.CharField(blank=True, max_length=10, null=True)),
                ('Locked', models.BooleanField(default=False)),
                ('Teacher_pref_status', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], max_length=1, null=True)),
                ('Theory_or_Lab', models.CharField(blank=True, choices=[('lab', 'Lab'), ('theory', 'Theory')], max_length=10, null=True)),
                ('Hard_slot', models.BooleanField(default=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
                ('Timetable_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisors.timetableheader')),
            ],
        ),
    ]
