# Generated by Django 5.1.2 on 2024-11-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherpreference',
            name='locked_schedule_slots',
        ),
    ]
