# Generated by Django 5.1.2 on 2025-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreferenceconstraints',
            name='End_Time',
        ),
        migrations.RemoveField(
            model_name='coursepreferenceconstraints',
            name='Start_Time',
        ),
        migrations.RemoveField(
            model_name='timetabledetail',
            name='End_Time',
        ),
        migrations.RemoveField(
            model_name='timetabledetail',
            name='Start_Time',
        ),
        migrations.AddField(
            model_name='coursepreferenceconstraints',
            name='End_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepreferenceconstraints',
            name='Start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetabledetail',
            name='End_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetabledetail',
            name='Start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
