# Generated by Django 5.1.2 on 2025-01-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compensatory_ID', models.IntegerField(unique=True)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('Section', models.CharField(blank=True, max_length=50, null=True)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreferenceConstraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference_ID', models.IntegerField(unique=True)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Lab_or_Theory', models.CharField(choices=[('lab', 'Lab'), ('theory', 'Theory')], max_length=10)),
                ('Multimedia_requirement', models.BooleanField(default=False)),
                ('Speaker', models.BooleanField(default=False)),
                ('Hard_constraint', models.BooleanField(default=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRoomPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Preference_ID', models.IntegerField(unique=True)),
                ('Room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Preference_details', models.CharField(blank=True, max_length=255, null=True)),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail_ID', models.IntegerField(unique=True)),
                ('Day', models.CharField(blank=True, max_length=10, null=True)),
                ('Start_Time', models.TimeField(blank=True, null=True)),
                ('End_Time', models.TimeField(blank=True, null=True)),
                ('Locked', models.BooleanField(default=False)),
                ('Teacher_pref_status', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow')], max_length=1, null=True)),
                ('Theory_or_Lab', models.CharField(blank=True, choices=[('lab', 'Lab'), ('theory', 'Theory')], max_length=10, null=True)),
                ('Hard_slot', models.BooleanField(default=False)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('Room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timetable_ID', models.IntegerField(unique=True)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('Batch_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('Section_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='course',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='room',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='section',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='preferred_rooms',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='preferred_subjects',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='section',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TimetableGenerationLog',
        ),
        migrations.AddField(
            model_name='timetabledetail',
            name='Timetable_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisors.timetableheader'),
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='TeacherPreference',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
