# Generated by Django 5.1.2 on 2024-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_remove_teacherpreference_locked_schedule_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
