# Generated by Django 5.1.2 on 2025-02-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_remove_coursepreferenceconstraints_end_time_and_more'),
        ('users', '0011_batchcourseteacherassignment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreferenceconstraints',
            name='Day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coursepreferenceconstraints',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section'),
        ),
    ]
