# Generated by Django 5.1.2 on 2025-02-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0003_coursepreferenceconstraints_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreferenceconstraints',
            name='Date',
        ),
    ]
