# Generated by Django 5.1.2 on 2025-03-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0004_remove_coursepreferenceconstraints_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabledetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timetableheader',
            name='id',
        ),
        migrations.AlterField(
            model_name='timetabledetail',
            name='Detail_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timetableheader',
            name='Timetable_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
