# Generated by Django 5.1.2 on 2025-03-11 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_remove_timetabledetail_id_remove_timetableheader_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('Generation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Time_Generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='timetableheader',
            name='Generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisors.generation'),
        ),
    ]
