# Generated by Django 5.1.2 on 2025-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0007_alter_timetableheader_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledetail',
            name='Teacher_pref_status',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow'), ('H', 'Blue')], max_length=1, null=True),
        ),
    ]
