# Generated by Django 5.1.2 on 2025-03-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0008_alter_timetabledetail_teacher_pref_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDay',
            fields=[
                ('disabled_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=10)),
                ('Timetable_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_days', to='advisors.timetableheader')),
            ],
        ),
    ]
