# Generated by Django 5.1.2 on 2025-03-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0009_disabledday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabledDay',
        ),
    ]
