# Generated by Django 5.1.2 on 2025-03-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0010_delete_disabledday'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableheader',
            name='disabled_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
