# Generated by Django 5.1.2 on 2025-03-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0011_timetableheader_disabled_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatory',
            name='id',
        ),
        migrations.AlterField(
            model_name='compensatory',
            name='Compensatory_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
