# Generated by Django 5.1.2 on 2025-03-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0012_remove_compensatory_id_and_more'),
        ('users', '0011_batchcourseteacherassignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatory',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section'),
        ),
    ]
