# Generated by Django 5.1.2 on 2025-03-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0013_alter_compensatory_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensatory',
            old_name='Section',
            new_name='Section_ID',
        ),
    ]
