# Generated by Django 5.1.2 on 2025-03-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0014_rename_section_compensatory_section_id'),
        ('users', '0011_batchcourseteacherassignment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatory',
            name='Batch_ID',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
            preserve_default=False,
        ),
    ]
