# Generated by Django 5.1.2 on 2025-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0015_compensatory_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatory',
            name='Lab_or_Theory',
            field=models.CharField(blank=True, choices=[('lab', 'Lab'), ('theory', 'Theory')], max_length=10, null=True),
        ),
    ]
