# Generated by Django 5.1.2 on 2025-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0016_compensatory_lab_or_theory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatory',
            name='Date',
        ),
        migrations.AddField(
            model_name='compensatory',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
