# Generated by Django 5.1.2 on 2025-03-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0017_remove_compensatory_date_compensatory_week_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensatory',
            old_name='week_number',
            new_name='Week_number',
        ),
    ]
