# Generated by Django 5.1.2 on 2025-03-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0018_rename_week_number_compensatory_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatory',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
    ]
