# Generated by Django 5.1.2 on 2025-03-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0021_generation_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='last_edited_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
