# Generated by Django 5.1.2 on 2025-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0022_alter_generation_last_edited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Lab_day_selection', models.IntegerField(choices=[(1, 'Monday & Wednesday Lab days for 2nd and 4th year and Tuesday and Thursday Lab days for 1st and 3rd Year'), (2, 'Tuesday and Thursday Lab days for 2nd and 4th Year and Monday and Wednesday Lab days for 1st and 3rd Year')])),
            ],
        ),
    ]
